/**
 * AgentTemplate 种子数据（与 platform mock 对齐，表为空时写入）
 */
import { prisma } from './prismaClient'

const now = (): string => new Date().toISOString().slice(0, 19).replace('T', ' ')

const SEED_TEMPLATES = [
  {
    id: 'at-base-content-creator',
    name: 'Base Content Creator Agent',
    nameZh: '内容生成 Agent',
    code: 'BASE_CONTENT_CREATOR',
    roleType: 'creator',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedProjectTypeIds: '["pt-account-operation","pt-client-acquisition"]',
    supportedGoalTypeIds: '["gt-account-followers","gt-account-engagement"]',
    supportedSkillIds: '["skill-content-write","skill-image-gen"]',
    defaultExecutorType: 'agent',
    temperature: 0.7,
    maxTokens: 4096,
    manual: true,
    semi_auto: true,
    full_auto: false,
  },
  {
    id: 'at-base-reviewer',
    name: 'Base Reviewer Agent',
    nameZh: '基础审核 Agent',
    code: 'BASE_REVIEWER',
    roleType: 'reviewer',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedSkillIds: '["skill-content-review","skill-compliance-check"]',
    defaultExecutorType: 'agent',
    temperature: 0.3,
    maxTokens: 2048,
    manual: true,
    semi_auto: true,
    full_auto: false,
  },
  {
    id: 'at-facebook-content-creator',
    platformType: 'facebook',
    name: 'Facebook Content Creator Agent',
    nameZh: 'Facebook 内容生成 Agent',
    code: 'FB_CONTENT_CREATOR',
    roleType: 'creator',
    category: 'execution',
    status: 'active',
    version: 1,
    parentTemplateId: 'at-base-content-creator',
    sourceTemplateId: 'at-base-content-creator',
    sourceVersion: '1.0',
    supportedProjectTypeIds: '["pt-account-operation"]',
    supportedSkillIds: '["skill-content-write","skill-image-gen","skill-fb-optimize"]',
    defaultExecutorType: 'agent',
    temperature: 0.7,
    maxTokens: 4096,
    manual: true,
    semi_auto: true,
    full_auto: false,
  },
  {
    id: 'at-content-reviewer',
    name: 'Content Reviewer Agent',
    nameZh: '内容审核 Agent',
    code: 'CONTENT_REVIEWER',
    roleType: 'reviewer',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedSkillIds: '["skill-content-review","skill-compliance-check","skill-brand-check"]',
    defaultExecutorType: 'agent',
    temperature: 0.2,
    maxTokens: 2048,
    manual: true,
    semi_auto: true,
    full_auto: false,
  },
  {
    id: 'at-publisher',
    name: 'Publisher Agent',
    nameZh: '发布 Agent',
    code: 'PUBLISHER',
    roleType: 'publisher',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedSkillIds: '["skill-publish","skill-schedule"]',
    defaultExecutorType: 'agent',
    temperature: 0.1,
    maxTokens: 1024,
    manual: true,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-workflow-planner',
    name: 'Base Workflow Planner Agent',
    nameZh: '基础流程规划助手',
    code: 'WORKFLOW_PLANNER',
    roleType: 'planner',
    category: 'planning',
    status: 'active',
    version: 1,
    plannerDomain: 'general',
    plannerTier: 'base',
    changeSummary: '["通用 SOP 解析与草案生成","通用变更摘要与风险提示"]',
    capabilityNotes: '适用于通用 ProjectType、GoalType、DeliverableMode。',
    supportedProjectTypeIds: '["pt-account-operation","pt-website-operation","pt-client-acquisition"]',
    supportedGoalTypeIds: '["gt-account-followers","gt-account-engagement","gt-index-count","gt-website-traffic","gt-lead-generation"]',
    supportedSkillIds: '["skill-parse-sop","skill-generate-draft","skill-revise-draft","skill-summarize-changes","skill-suggest-agent-bindings"]',
    defaultExecutorType: 'agent',
    temperature: 0.5,
    maxTokens: 8192,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-social-workflow-planner',
    name: 'Social Workflow Planner Agent',
    nameZh: '社媒运营流程规划助手',
    code: 'SOCIAL_WORKFLOW_PLANNER',
    roleType: 'planner',
    category: 'planning',
    status: 'active',
    version: 1,
    parentTemplateId: 'at-workflow-planner',
    sourceTemplateId: 'at-workflow-planner',
    sourceVersion: '1.0',
    plannerDomain: 'social',
    plannerTier: 'domain',
    changeSummary: '["社媒内容节奏、审核链、发布后追踪"]',
    supportedProjectTypeIds: '["pt-account-operation"]',
    supportedSkillIds: '["skill-content-write","skill-content-review","skill-publish","skill-metrics-write"]',
    defaultExecutorType: 'agent',
    temperature: 0.5,
    maxTokens: 8192,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-website-workflow-planner',
    name: 'Website Workflow Planner Agent',
    nameZh: '建站流程规划助手',
    code: 'WEBSITE_WORKFLOW_PLANNER',
    roleType: 'planner',
    category: 'planning',
    status: 'active',
    version: 1,
    parentTemplateId: 'at-workflow-planner',
    sourceTemplateId: 'at-workflow-planner',
    sourceVersion: '1.0',
    plannerDomain: 'website',
    plannerTier: 'domain',
    supportedProjectTypeIds: '["pt-website-operation"]',
    supportedSkillIds: '["skill-keyword-research","skill-content-write","skill-data-fetch"]',
    defaultExecutorType: 'agent',
    temperature: 0.5,
    maxTokens: 8192,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-ai-employee-workflow-planner',
    name: 'AI Employee Workflow Planner Agent',
    nameZh: 'AI 员工流程规划助手',
    code: 'AI_EMPLOYEE_WORKFLOW_PLANNER',
    roleType: 'planner',
    category: 'planning',
    status: 'active',
    version: 1,
    parentTemplateId: 'at-workflow-planner',
    sourceTemplateId: 'at-workflow-planner',
    sourceVersion: '1.0',
    plannerDomain: 'ai_employee',
    plannerTier: 'domain',
    supportedSkillIds: '["skill-parse-sop","skill-generate-draft","skill-summarize-changes"]',
    defaultExecutorType: 'agent',
    temperature: 0.5,
    maxTokens: 8192,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-performance-recorder',
    name: 'Performance Recorder Agent',
    nameZh: '结果记录 Agent',
    code: 'PERFORMANCE_RECORDER',
    roleType: 'recorder',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedSkillIds: '["skill-data-fetch","skill-metrics-write"]',
    defaultExecutorType: 'agent',
    temperature: 0,
    maxTokens: 4096,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
  {
    id: 'at-research-search',
    name: 'Research & Search Agent',
    nameZh: '研究/搜索 Agent',
    code: 'RESEARCH_SEARCH',
    roleType: 'other',
    category: 'execution',
    status: 'active',
    version: 1,
    supportedSkillIds: '["skill-keyword-research","skill-data-fetch"]',
    defaultExecutorType: 'agent',
    temperature: 0.5,
    maxTokens: 8192,
    manual: true,
    semi_auto: true,
    full_auto: false,
  },
  {
    id: 'at-execution-supervisor',
    name: 'Execution Supervisor Agent',
    nameZh: '执行监督助手',
    code: 'EXECUTION_SUPERVISOR',
    roleType: 'supervisor',
    category: 'coordination',
    status: 'active',
    version: 1,
    supportedSkillIds: '[]',
    defaultExecutorType: 'agent',
    temperature: 0.3,
    maxTokens: 4096,
    manual: false,
    semi_auto: true,
    full_auto: true,
  },
]

function defaultTemplateRow(partial: Record<string, unknown>) {
  const ts = now()
  return {
    name: '',
    nameZh: null as string | null,
    code: '',
    description: null as string | null,
    roleType: 'other',
    category: null,
    domain: null,
    sceneTags: null,
    platformType: null,
    archetypeCode: null,
    parentTemplateId: null,
    sourceTemplateId: null,
    sourceVersion: null,
    status: 'draft',
    version: 1,
    isLatest: true,
    isSystemPreset: true,
    isCloneable: true,
    supportedProjectTypeIds: null,
    supportedGoalTypeIds: null,
    supportedSkillIds: null,
    defaultExecutorType: 'agent',
    allowedExecutorTypes: null,
    allowedTerminalTypes: null,
    defaultModelKey: null,
    fallbackModelKeys: null,
    temperature: null,
    maxTokens: null,
    systemPromptTemplate: null,
    instructionTemplate: null,
    outputFormat: null,
    requireGoalContext: false,
    requireIdentityContext: false,
    requireSOPContext: false,
    requireStructuredOutput: false,
    disallowDirectTerminalAction: true,
    requireHumanReview: false,
    requireNodeReview: false,
    autoApproveWhenConfidenceGte: null,
    plannerDomain: null,
    plannerTier: null,
    changeSummary: null,
    capabilityNotes: null,
    notes: null,
    manual: true,
    semi_auto: true,
    full_auto: false,
    createdAt: ts,
    updatedAt: ts,
    ...partial,
  }
}

export async function seedAgentTemplatesIfEmpty(): Promise<void> {
  const count = await prisma.agentTemplate.count()
  if (count > 0) return
  const ts = now()
  for (const t of SEED_TEMPLATES) {
    await prisma.agentTemplate.create({
      data: defaultTemplateRow({
        id: t.id,
        name: t.name,
        nameZh: t.nameZh,
        code: t.code,
        roleType: t.roleType,
        category: t.category,
        status: t.status,
        version: t.version,
        supportedProjectTypeIds: t.supportedProjectTypeIds ?? null,
        supportedGoalTypeIds: t.supportedGoalTypeIds ?? null,
        supportedSkillIds: t.supportedSkillIds ?? null,
        defaultExecutorType: t.defaultExecutorType,
        temperature: t.temperature,
        maxTokens: t.maxTokens,
        parentTemplateId: t.parentTemplateId ?? null,
        sourceTemplateId: t.sourceTemplateId ?? null,
        sourceVersion: t.sourceVersion ?? null,
        plannerDomain: t.plannerDomain ?? null,
        plannerTier: t.plannerTier ?? null,
        changeSummary: t.changeSummary ?? null,
        capabilityNotes: t.capabilityNotes ?? null,
        platformType: (t as Record<string, unknown>).platformType ?? null,
        manual: t.manual,
        semi_auto: t.semi_auto,
        full_auto: t.full_auto,
        createdAt: ts,
        updatedAt: ts,
      }),
    })
  }
}
