/**
 * 终端类型工厂种子数据（11 条预设终端类型），表为空时写入
 */
import { prisma } from './prismaClient'

const now = (): string => new Date().toISOString().slice(0, 19).replace('T', ' ')

const SEED_TERMINAL_TYPES = [
  {
    id: 'stt-fb-page-api',
    name: 'Facebook Page API',
    nameZh: 'Facebook 公共主页 API',
    code: 'fb-page-api',
    typeCategory: 'api',
    icon: 'fb',
    description: '通过 Facebook Graph API 管理公共主页内容与互动',
    authSchema: '{"type":"object","properties":{"accessToken":{"type":"string","description":"页面访问令牌"},"pageId":{"type":"string","description":"公共主页 ID"}},"required":["accessToken","pageId"]}',
    configSchema: '{"type":"object","properties":{"region":{"type":"string","description":"区域代码"}}}',
    supportedProjectTypeIds: '["pt-account-operation"]',
    capabilityTags: '["post_content","read_metrics","reply_comment","publish"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-instagram-api',
    name: 'Instagram Graph API',
    nameZh: 'Instagram Graph API',
    code: 'instagram-api',
    typeCategory: 'api',
    icon: 'instagram',
    description: '通过 Instagram Graph API 管理账号内容与洞察',
    authSchema: '{"type":"object","properties":{"accessToken":{"type":"string","description":"访问令牌"},"instagramBusinessAccountId":{"type":"string","description":"Instagram 商业账号 ID"}},"required":["accessToken","instagramBusinessAccountId"]}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-account-operation"]',
    capabilityTags: '["post_content","read_metrics","story"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-x-api-v2',
    name: 'X API v2',
    nameZh: 'X（推特）API v2',
    code: 'x-api-v2',
    typeCategory: 'api',
    icon: 'x',
    description: '通过 X API v2 发布推文与读取互动数据',
    authSchema: '{"type":"object","properties":{"bearerToken":{"type":"string","description":"Bearer Token"},"apiKey":{"type":"string","description":"API Key"},"apiSecret":{"type":"string","description":"API Secret"}},"required":["bearerToken"]}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-account-operation"]',
    capabilityTags: '["post_content","read_metrics","reply"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-tiktok-api',
    name: 'TikTok Content API',
    nameZh: 'TikTok 内容 API',
    code: 'tiktok-api',
    typeCategory: 'api',
    icon: 'tiktok',
    description: '通过 TikTok 内容 API 管理视频发布与数据',
    authSchema: '{"type":"object","properties":{"accessToken":{"type":"string","description":"访问令牌"},"openId":{"type":"string","description":"Open ID"}},"required":["accessToken"]}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-account-operation"]',
    capabilityTags: '["post_content","read_metrics","upload_video"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-linkedin-api',
    name: 'LinkedIn Content API',
    nameZh: 'LinkedIn 内容 API',
    code: 'linkedin-api',
    typeCategory: 'api',
    icon: 'linkedin',
    description: '通过 LinkedIn API 发布内容与获取线索',
    authSchema: '{"type":"object","properties":{"accessToken":{"type":"string","description":"OAuth 访问令牌"}},"required":["accessToken"]}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-client-acquisition"]',
    capabilityTags: '["post_content","read_metrics","lead_gen"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-whatsapp-business-api',
    name: 'WhatsApp Business API',
    nameZh: 'WhatsApp Business API',
    code: 'whatsapp-business-api',
    typeCategory: 'api',
    icon: 'whatsapp',
    description: '通过 WhatsApp Business API 发送消息与管理会话',
    authSchema: '{"type":"object","properties":{"accessToken":{"type":"string","description":"访问令牌"},"phoneNumberId":{"type":"string","description":"电话号码 ID"}},"required":["accessToken","phoneNumberId"]}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-client-acquisition"]',
    capabilityTags: '["send_message","receive_message","template"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-custom-rest-api',
    name: 'Custom REST API',
    nameZh: '自定义 REST API',
    code: 'custom-rest-api',
    typeCategory: 'api',
    icon: 'api',
    description: '连接任意符合 REST 规范的 API 端点',
    authSchema: '{"type":"object","properties":{"apiKey":{"type":"string","description":"API Key"},"baseUrl":{"type":"string","description":"Base URL"}},"required":["baseUrl"]}',
    configSchema: '{"type":"object","properties":{"timeoutMs":{"type":"number","description":"超时毫秒"}}}',
    supportedProjectTypeIds: '["pt-account-operation","pt-website-operation","pt-client-acquisition"]',
    capabilityTags: '["custom"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-chrome-automation',
    name: 'Chrome Browser Automation',
    nameZh: 'Chrome 浏览器自动化',
    code: 'chrome-automation',
    typeCategory: 'browser',
    icon: 'chrome',
    description: '通过 Playwright/Selenium 控制 Chrome 完成 Web 操作',
    authSchema: '{}',
    configSchema: '{"type":"object","properties":{"headless":{"type":"boolean","description":"无头模式"},"viewport":{"type":"string","description":"视口尺寸"}}}',
    supportedProjectTypeIds: '["pt-website-operation"]',
    capabilityTags: '["browse","screenshot","form_submit","seo_check"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-edge-headless',
    name: 'Edge Headless Browser',
    nameZh: 'Edge 无头浏览器',
    code: 'edge-headless',
    typeCategory: 'browser',
    icon: 'edge',
    description: '通过 Edge 无头模式执行 Web 自动化任务',
    authSchema: '{}',
    configSchema: '{"type":"object","properties":{"headless":{"type":"boolean"}}}',
    supportedProjectTypeIds: '["pt-website-operation"]',
    capabilityTags: '["browse","screenshot","automation"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-windows-mcp',
    name: 'Windows MCP Control',
    nameZh: 'Windows MCP 控制',
    code: 'windows-mcp',
    typeCategory: 'mcp',
    icon: 'windows',
    description: '通过 MCP 协议控制 Windows 桌面完成复杂多步任务',
    authSchema: '{"type":"object","properties":{"mcpEndpoint":{"type":"string","description":"MCP 服务端点"}}}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-account-operation","pt-website-operation","pt-client-acquisition"]',
    capabilityTags: '["desktop_automation","file_system","ui_control"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
  {
    id: 'stt-macos-mcp',
    name: 'macOS MCP Control',
    nameZh: 'macOS MCP 控制',
    code: 'macos-mcp',
    typeCategory: 'mcp',
    icon: 'apple',
    description: '通过 MCP 协议控制 macOS 桌面完成复杂多步任务',
    authSchema: '{"type":"object","properties":{"mcpEndpoint":{"type":"string","description":"MCP 服务端点"}}}',
    configSchema: '{}',
    supportedProjectTypeIds: '["pt-account-operation","pt-website-operation","pt-client-acquisition"]',
    capabilityTags: '["desktop_automation","file_system","ui_control"]',
    status: 'active',
    isSystemPreset: true,
    version: '1.0',
  },
]

export async function seedSystemTerminalTypesIfEmpty(): Promise<void> {
  const count = await prisma.systemTerminalType.count()
  if (count > 0) return
  const ts = now()
  for (const t of SEED_TERMINAL_TYPES) {
    await prisma.systemTerminalType.create({
      data: {
        id: t.id,
        name: t.name,
        nameZh: t.nameZh,
        code: t.code,
        typeCategory: t.typeCategory,
        icon: t.icon,
        description: t.description,
        authSchema: t.authSchema,
        configSchema: t.configSchema,
        supportedProjectTypeIds: t.supportedProjectTypeIds,
        capabilityTags: t.capabilityTags,
        status: t.status,
        isSystemPreset: t.isSystemPreset,
        version: t.version,
        createdAt: ts,
        updatedAt: ts,
      },
    })
  }
}
